/* This file was generated by hpbc (the hpb compiler) from the input
 * file:
 *
 *     google/protobuf/compiler/plugin.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#ifndef GOOGLE_PROTOBUF_COMPILER_PLUGIN_PROTO_HPB_H_
#define GOOGLE_PROTOBUF_COMPILER_PLUGIN_PROTO_HPB_H_

#include "hpb/generated_code_support.h"

// Must be last. 
#include "hpb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct google_protobuf_compiler_Version google_protobuf_compiler_Version;
typedef struct google_protobuf_compiler_CodeGeneratorRequest google_protobuf_compiler_CodeGeneratorRequest;
typedef struct google_protobuf_compiler_CodeGeneratorResponse google_protobuf_compiler_CodeGeneratorResponse;
typedef struct google_protobuf_compiler_CodeGeneratorResponse_File google_protobuf_compiler_CodeGeneratorResponse_File;
extern const hpb_MiniTable* google_protobuf_compiler_Version_msg_init();
extern const hpb_MiniTable* google_protobuf_compiler_CodeGeneratorRequest_msg_init();
extern const hpb_MiniTable* google_protobuf_compiler_CodeGeneratorResponse_msg_init();
extern const hpb_MiniTable* google_protobuf_compiler_CodeGeneratorResponse_File_msg_init();
struct google_protobuf_FileDescriptorProto;
struct google_protobuf_GeneratedCodeInfo;
extern const hpb_MiniTable* google_protobuf_FileDescriptorProto_msg_init();
extern const hpb_MiniTable* google_protobuf_GeneratedCodeInfo_msg_init();

typedef enum {
  google_protobuf_compiler_CodeGeneratorResponse_FEATURE_NONE = 0,
  google_protobuf_compiler_CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL = 1
} google_protobuf_compiler_CodeGeneratorResponse_Feature;


extern const hpb_MiniTableEnum* google_protobuf_compiler_CodeGeneratorResponse_Feature_enum_init();

/* google.protobuf.compiler.Version */

HPB_INLINE google_protobuf_compiler_Version* google_protobuf_compiler_Version_new(hpb_Arena* arena) {
  return (google_protobuf_compiler_Version*)_hpb_Message_New(google_protobuf_compiler_Version_msg_init(), arena);
}
HPB_INLINE google_protobuf_compiler_Version* google_protobuf_compiler_Version_parse(const char* buf, size_t size, hpb_Arena* arena) {
  google_protobuf_compiler_Version* ret = google_protobuf_compiler_Version_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_Version_msg_init(), NULL, 0, arena) != kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE google_protobuf_compiler_Version* google_protobuf_compiler_Version_parse_ex(const char* buf, size_t size,
                           const hpb_ExtensionRegistry* extreg,
                           int options, hpb_Arena* arena) {
  google_protobuf_compiler_Version* ret = google_protobuf_compiler_Version_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_Version_msg_init(), extreg, options, arena) !=
      kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE char* google_protobuf_compiler_Version_serialize(const google_protobuf_compiler_Version* msg, hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_Version_msg_init(), 0, arena, &ptr, len);
  return ptr;
}
HPB_INLINE char* google_protobuf_compiler_Version_serialize_ex(const google_protobuf_compiler_Version* msg, int options,
                                 hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_Version_msg_init(), options, arena, &ptr, len);
  return ptr;
}
HPB_INLINE void google_protobuf_compiler_Version_clear_major(google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 1);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE int32_t google_protobuf_compiler_Version_major(const google_protobuf_compiler_Version* msg) {
  int32_t default_val = (int32_t)0;
  int32_t ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 1);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_Version_has_major(const google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 1);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_Version_clear_minor(google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 2);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE int32_t google_protobuf_compiler_Version_minor(const google_protobuf_compiler_Version* msg) {
  int32_t default_val = (int32_t)0;
  int32_t ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 2);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_Version_has_minor(const google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 2);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_Version_clear_patch(google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 3);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE int32_t google_protobuf_compiler_Version_patch(const google_protobuf_compiler_Version* msg) {
  int32_t default_val = (int32_t)0;
  int32_t ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 3);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_Version_has_patch(const google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 3);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_Version_clear_suffix(google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 4);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView google_protobuf_compiler_Version_suffix(const google_protobuf_compiler_Version* msg) {
  hpb_StringView default_val = hpb_StringView_FromString("");
  hpb_StringView ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 4);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_Version_has_suffix(const google_protobuf_compiler_Version* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 4);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}

HPB_INLINE void google_protobuf_compiler_Version_set_major(google_protobuf_compiler_Version *msg, int32_t value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 1);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_Version_set_minor(google_protobuf_compiler_Version *msg, int32_t value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 2);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_Version_set_patch(google_protobuf_compiler_Version *msg, int32_t value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 3);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_Version_set_suffix(google_protobuf_compiler_Version *msg, hpb_StringView value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_Version_msg_init(), 4);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}

/* google.protobuf.compiler.CodeGeneratorRequest */

HPB_INLINE google_protobuf_compiler_CodeGeneratorRequest* google_protobuf_compiler_CodeGeneratorRequest_new(hpb_Arena* arena) {
  return (google_protobuf_compiler_CodeGeneratorRequest*)_hpb_Message_New(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), arena);
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorRequest* google_protobuf_compiler_CodeGeneratorRequest_parse(const char* buf, size_t size, hpb_Arena* arena) {
  google_protobuf_compiler_CodeGeneratorRequest* ret = google_protobuf_compiler_CodeGeneratorRequest_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_CodeGeneratorRequest_msg_init(), NULL, 0, arena) != kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorRequest* google_protobuf_compiler_CodeGeneratorRequest_parse_ex(const char* buf, size_t size,
                           const hpb_ExtensionRegistry* extreg,
                           int options, hpb_Arena* arena) {
  google_protobuf_compiler_CodeGeneratorRequest* ret = google_protobuf_compiler_CodeGeneratorRequest_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_CodeGeneratorRequest_msg_init(), extreg, options, arena) !=
      kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE char* google_protobuf_compiler_CodeGeneratorRequest_serialize(const google_protobuf_compiler_CodeGeneratorRequest* msg, hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 0, arena, &ptr, len);
  return ptr;
}
HPB_INLINE char* google_protobuf_compiler_CodeGeneratorRequest_serialize_ex(const google_protobuf_compiler_CodeGeneratorRequest* msg, int options,
                                 hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_CodeGeneratorRequest_msg_init(), options, arena, &ptr, len);
  return ptr;
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorRequest_clear_file_to_generate(google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 1);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView const* google_protobuf_compiler_CodeGeneratorRequest_file_to_generate(const google_protobuf_compiler_CodeGeneratorRequest* msg, size_t* size) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 1);
  const hpb_Array* arr = hpb_Message_GetArray(msg, &field);
  if (arr) {
    if (size) *size = arr->size;
    return (hpb_StringView const*)_hpb_array_constptr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorRequest_has_file_to_generate(const google_protobuf_compiler_CodeGeneratorRequest* msg) {
  size_t size;
  google_protobuf_compiler_CodeGeneratorRequest_file_to_generate(msg, &size);
  return size != 0;
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorRequest_clear_parameter(google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 2);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView google_protobuf_compiler_CodeGeneratorRequest_parameter(const google_protobuf_compiler_CodeGeneratorRequest* msg) {
  hpb_StringView default_val = hpb_StringView_FromString("");
  hpb_StringView ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 2);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorRequest_has_parameter(const google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 2);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorRequest_clear_compiler_version(google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 3);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE const google_protobuf_compiler_Version* google_protobuf_compiler_CodeGeneratorRequest_compiler_version(const google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const google_protobuf_compiler_Version* default_val = NULL;
  const google_protobuf_compiler_Version* ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 3);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorRequest_has_compiler_version(const google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 3);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorRequest_clear_proto_file(google_protobuf_compiler_CodeGeneratorRequest* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 15);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE const struct google_protobuf_FileDescriptorProto* const* google_protobuf_compiler_CodeGeneratorRequest_proto_file(const google_protobuf_compiler_CodeGeneratorRequest* msg, size_t* size) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 15);
  const hpb_Array* arr = hpb_Message_GetArray(msg, &field);
  if (arr) {
    if (size) *size = arr->size;
    return (const struct google_protobuf_FileDescriptorProto* const*)_hpb_array_constptr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorRequest_has_proto_file(const google_protobuf_compiler_CodeGeneratorRequest* msg) {
  size_t size;
  google_protobuf_compiler_CodeGeneratorRequest_proto_file(msg, &size);
  return size != 0;
}

HPB_INLINE hpb_StringView* google_protobuf_compiler_CodeGeneratorRequest_mutable_file_to_generate(google_protobuf_compiler_CodeGeneratorRequest* msg, size_t* size) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 1);
  hpb_Array* arr = hpb_Message_GetMutableArray(msg, &field);
  if (arr) {
    if (size) *size = arr->size;
    return (hpb_StringView*)_hpb_array_ptr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}
HPB_INLINE hpb_StringView* google_protobuf_compiler_CodeGeneratorRequest_resize_file_to_generate(google_protobuf_compiler_CodeGeneratorRequest* msg, size_t size, hpb_Arena* arena) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 1);
  return (hpb_StringView*)hpb_Message_ResizeArrayUninitialized(msg, &field, size, arena);
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorRequest_add_file_to_generate(google_protobuf_compiler_CodeGeneratorRequest* msg, hpb_StringView val, hpb_Arena* arena) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 1);
  hpb_Array* arr = hpb_Message_GetOrCreateMutableArray(msg, &field, arena);
  if (!arr || !_hpb_Array_ResizeUninitialized(arr, arr->size + 1, arena)) {
    return false;
  }
  _hpb_Array_Set(arr, arr->size - 1, &val, sizeof(val));
  return true;
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorRequest_set_parameter(google_protobuf_compiler_CodeGeneratorRequest *msg, hpb_StringView value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 2);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorRequest_set_compiler_version(google_protobuf_compiler_CodeGeneratorRequest *msg, google_protobuf_compiler_Version* value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 3);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE struct google_protobuf_compiler_Version* google_protobuf_compiler_CodeGeneratorRequest_mutable_compiler_version(google_protobuf_compiler_CodeGeneratorRequest* msg, hpb_Arena* arena) {
  struct google_protobuf_compiler_Version* sub = (struct google_protobuf_compiler_Version*)google_protobuf_compiler_CodeGeneratorRequest_compiler_version(msg);
  if (sub == NULL) {
    sub = (struct google_protobuf_compiler_Version*)_hpb_Message_New(google_protobuf_compiler_Version_msg_init(), arena);
    if (sub) google_protobuf_compiler_CodeGeneratorRequest_set_compiler_version(msg, sub);
  }
  return sub;
}
HPB_INLINE struct google_protobuf_FileDescriptorProto** google_protobuf_compiler_CodeGeneratorRequest_mutable_proto_file(google_protobuf_compiler_CodeGeneratorRequest* msg, size_t* size) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 15);
  hpb_Array* arr = hpb_Message_GetMutableArray(msg, &field);
  if (arr) {
    if (size) *size = arr->size;
    return (struct google_protobuf_FileDescriptorProto**)_hpb_array_ptr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}
HPB_INLINE struct google_protobuf_FileDescriptorProto** google_protobuf_compiler_CodeGeneratorRequest_resize_proto_file(google_protobuf_compiler_CodeGeneratorRequest* msg, size_t size, hpb_Arena* arena) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 15);
  return (struct google_protobuf_FileDescriptorProto**)hpb_Message_ResizeArrayUninitialized(msg, &field, size, arena);
}
HPB_INLINE struct google_protobuf_FileDescriptorProto* google_protobuf_compiler_CodeGeneratorRequest_add_proto_file(google_protobuf_compiler_CodeGeneratorRequest* msg, hpb_Arena* arena) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorRequest_msg_init(), 15);
  hpb_Array* arr = hpb_Message_GetOrCreateMutableArray(msg, &field, arena);
  if (!arr || !_hpb_Array_ResizeUninitialized(arr, arr->size + 1, arena)) {
    return NULL;
  }
  struct google_protobuf_FileDescriptorProto* sub = (struct google_protobuf_FileDescriptorProto*)_hpb_Message_New(google_protobuf_FileDescriptorProto_msg_init(), arena);
  if (!arr || !sub) return NULL;
  _hpb_Array_Set(arr, arr->size - 1, &sub, sizeof(sub));
  return sub;
}

/* google.protobuf.compiler.CodeGeneratorResponse */

HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse* google_protobuf_compiler_CodeGeneratorResponse_new(hpb_Arena* arena) {
  return (google_protobuf_compiler_CodeGeneratorResponse*)_hpb_Message_New(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), arena);
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse* google_protobuf_compiler_CodeGeneratorResponse_parse(const char* buf, size_t size, hpb_Arena* arena) {
  google_protobuf_compiler_CodeGeneratorResponse* ret = google_protobuf_compiler_CodeGeneratorResponse_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_CodeGeneratorResponse_msg_init(), NULL, 0, arena) != kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse* google_protobuf_compiler_CodeGeneratorResponse_parse_ex(const char* buf, size_t size,
                           const hpb_ExtensionRegistry* extreg,
                           int options, hpb_Arena* arena) {
  google_protobuf_compiler_CodeGeneratorResponse* ret = google_protobuf_compiler_CodeGeneratorResponse_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_CodeGeneratorResponse_msg_init(), extreg, options, arena) !=
      kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE char* google_protobuf_compiler_CodeGeneratorResponse_serialize(const google_protobuf_compiler_CodeGeneratorResponse* msg, hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 0, arena, &ptr, len);
  return ptr;
}
HPB_INLINE char* google_protobuf_compiler_CodeGeneratorResponse_serialize_ex(const google_protobuf_compiler_CodeGeneratorResponse* msg, int options,
                                 hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_CodeGeneratorResponse_msg_init(), options, arena, &ptr, len);
  return ptr;
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_clear_error(google_protobuf_compiler_CodeGeneratorResponse* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 1);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView google_protobuf_compiler_CodeGeneratorResponse_error(const google_protobuf_compiler_CodeGeneratorResponse* msg) {
  hpb_StringView default_val = hpb_StringView_FromString("");
  hpb_StringView ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 1);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_has_error(const google_protobuf_compiler_CodeGeneratorResponse* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 1);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_clear_supported_features(google_protobuf_compiler_CodeGeneratorResponse* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 2);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE uint64_t google_protobuf_compiler_CodeGeneratorResponse_supported_features(const google_protobuf_compiler_CodeGeneratorResponse* msg) {
  uint64_t default_val = (uint64_t)0ull;
  uint64_t ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 2);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_has_supported_features(const google_protobuf_compiler_CodeGeneratorResponse* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 2);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_clear_file(google_protobuf_compiler_CodeGeneratorResponse* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 15);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE const google_protobuf_compiler_CodeGeneratorResponse_File* const* google_protobuf_compiler_CodeGeneratorResponse_file(const google_protobuf_compiler_CodeGeneratorResponse* msg, size_t* size) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 15);
  const hpb_Array* arr = hpb_Message_GetArray(msg, &field);
  if (arr) {
    if (size) *size = arr->size;
    return (const google_protobuf_compiler_CodeGeneratorResponse_File* const*)_hpb_array_constptr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_has_file(const google_protobuf_compiler_CodeGeneratorResponse* msg) {
  size_t size;
  google_protobuf_compiler_CodeGeneratorResponse_file(msg, &size);
  return size != 0;
}

HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_set_error(google_protobuf_compiler_CodeGeneratorResponse *msg, hpb_StringView value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 1);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_set_supported_features(google_protobuf_compiler_CodeGeneratorResponse *msg, uint64_t value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 2);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse_File** google_protobuf_compiler_CodeGeneratorResponse_mutable_file(google_protobuf_compiler_CodeGeneratorResponse* msg, size_t* size) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 15);
  hpb_Array* arr = hpb_Message_GetMutableArray(msg, &field);
  if (arr) {
    if (size) *size = arr->size;
    return (google_protobuf_compiler_CodeGeneratorResponse_File**)_hpb_array_ptr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse_File** google_protobuf_compiler_CodeGeneratorResponse_resize_file(google_protobuf_compiler_CodeGeneratorResponse* msg, size_t size, hpb_Arena* arena) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 15);
  return (google_protobuf_compiler_CodeGeneratorResponse_File**)hpb_Message_ResizeArrayUninitialized(msg, &field, size, arena);
}
HPB_INLINE struct google_protobuf_compiler_CodeGeneratorResponse_File* google_protobuf_compiler_CodeGeneratorResponse_add_file(google_protobuf_compiler_CodeGeneratorResponse* msg, hpb_Arena* arena) {
  hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_msg_init(), 15);
  hpb_Array* arr = hpb_Message_GetOrCreateMutableArray(msg, &field, arena);
  if (!arr || !_hpb_Array_ResizeUninitialized(arr, arr->size + 1, arena)) {
    return NULL;
  }
  struct google_protobuf_compiler_CodeGeneratorResponse_File* sub = (struct google_protobuf_compiler_CodeGeneratorResponse_File*)_hpb_Message_New(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), arena);
  if (!arr || !sub) return NULL;
  _hpb_Array_Set(arr, arr->size - 1, &sub, sizeof(sub));
  return sub;
}

/* google.protobuf.compiler.CodeGeneratorResponse.File */

HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse_File* google_protobuf_compiler_CodeGeneratorResponse_File_new(hpb_Arena* arena) {
  return (google_protobuf_compiler_CodeGeneratorResponse_File*)_hpb_Message_New(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), arena);
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse_File* google_protobuf_compiler_CodeGeneratorResponse_File_parse(const char* buf, size_t size, hpb_Arena* arena) {
  google_protobuf_compiler_CodeGeneratorResponse_File* ret = google_protobuf_compiler_CodeGeneratorResponse_File_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), NULL, 0, arena) != kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE google_protobuf_compiler_CodeGeneratorResponse_File* google_protobuf_compiler_CodeGeneratorResponse_File_parse_ex(const char* buf, size_t size,
                           const hpb_ExtensionRegistry* extreg,
                           int options, hpb_Arena* arena) {
  google_protobuf_compiler_CodeGeneratorResponse_File* ret = google_protobuf_compiler_CodeGeneratorResponse_File_new(arena);
  if (!ret) return NULL;
  if (hpb_Decode(buf, size, ret, google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), extreg, options, arena) !=
      kHpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
HPB_INLINE char* google_protobuf_compiler_CodeGeneratorResponse_File_serialize(const google_protobuf_compiler_CodeGeneratorResponse_File* msg, hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 0, arena, &ptr, len);
  return ptr;
}
HPB_INLINE char* google_protobuf_compiler_CodeGeneratorResponse_File_serialize_ex(const google_protobuf_compiler_CodeGeneratorResponse_File* msg, int options,
                                 hpb_Arena* arena, size_t* len) {
  char* ptr;
  (void)hpb_Encode(msg, google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), options, arena, &ptr, len);
  return ptr;
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_clear_name(google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 1);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView google_protobuf_compiler_CodeGeneratorResponse_File_name(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  hpb_StringView default_val = hpb_StringView_FromString("");
  hpb_StringView ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 1);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_File_has_name(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 1);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_clear_insertion_point(google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 2);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView google_protobuf_compiler_CodeGeneratorResponse_File_insertion_point(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  hpb_StringView default_val = hpb_StringView_FromString("");
  hpb_StringView ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 2);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_File_has_insertion_point(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 2);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_clear_content(google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 15);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE hpb_StringView google_protobuf_compiler_CodeGeneratorResponse_File_content(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  hpb_StringView default_val = hpb_StringView_FromString("");
  hpb_StringView ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 15);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_File_has_content(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 15);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_clear_generated_code_info(google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 16);
  _hpb_Message_ClearNonExtensionField(msg, &field);
}
HPB_INLINE const struct google_protobuf_GeneratedCodeInfo* google_protobuf_compiler_CodeGeneratorResponse_File_generated_code_info(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const struct google_protobuf_GeneratedCodeInfo* default_val = NULL;
  const struct google_protobuf_GeneratedCodeInfo* ret;
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 16);
  _hpb_Message_GetNonExtensionField(msg, &field, &default_val, &ret);
  return ret;
}
HPB_INLINE bool google_protobuf_compiler_CodeGeneratorResponse_File_has_generated_code_info(const google_protobuf_compiler_CodeGeneratorResponse_File* msg) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 16);
  return _hpb_Message_HasNonExtensionField(msg, &field);
}

HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_set_name(google_protobuf_compiler_CodeGeneratorResponse_File *msg, hpb_StringView value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 1);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_set_insertion_point(google_protobuf_compiler_CodeGeneratorResponse_File *msg, hpb_StringView value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 2);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_set_content(google_protobuf_compiler_CodeGeneratorResponse_File *msg, hpb_StringView value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 15);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE void google_protobuf_compiler_CodeGeneratorResponse_File_set_generated_code_info(google_protobuf_compiler_CodeGeneratorResponse_File *msg, struct google_protobuf_GeneratedCodeInfo* value) {
  const hpb_MiniTableField field = *hpb_MiniTable_FindFieldByNumber(google_protobuf_compiler_CodeGeneratorResponse_File_msg_init(), 16);
  _hpb_Message_SetNonExtensionField(msg, &field, &value);
}
HPB_INLINE struct google_protobuf_GeneratedCodeInfo* google_protobuf_compiler_CodeGeneratorResponse_File_mutable_generated_code_info(google_protobuf_compiler_CodeGeneratorResponse_File* msg, hpb_Arena* arena) {
  struct google_protobuf_GeneratedCodeInfo* sub = (struct google_protobuf_GeneratedCodeInfo*)google_protobuf_compiler_CodeGeneratorResponse_File_generated_code_info(msg);
  if (sub == NULL) {
    sub = (struct google_protobuf_GeneratedCodeInfo*)_hpb_Message_New(google_protobuf_GeneratedCodeInfo_msg_init(), arena);
    if (sub) google_protobuf_compiler_CodeGeneratorResponse_File_set_generated_code_info(msg, sub);
  }
  return sub;
}

extern const hpb_MiniTableFile google_protobuf_compiler_plugin_proto_hpb_file_layout;

#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "hpb/port/undef.inc"

#endif  /* GOOGLE_PROTOBUF_COMPILER_PLUGIN_PROTO_HPB_H_ */
