// Protocol Buffers - Google's data interchange format
// Copyright 2023 Google LLC.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google LLC nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This should #undef all macros #defined in def.inc

#undef HPB_SIZE
#undef HPB_PTR_AT
#undef HPB_MAPTYPE_STRING
#undef HPB_EXPORT
#undef HPB_INLINE
#undef HPB_API
#undef HPB_API_INLINE
#undef HPB_ALIGN_UP
#undef HPB_ALIGN_DOWN
#undef HPB_ALIGN_MALLOC
#undef HPB_ALIGN_OF
#undef HPB_MALLOC_ALIGN
#undef HPB_LIKELY
#undef HPB_UNLIKELY
#undef HPB_FORCEINLINE
#undef HPB_NOINLINE
#undef HPB_NORETURN
#undef HPB_PRINTF
#undef HPB_MAX
#undef HPB_MIN
#undef HPB_UNUSED
#undef HPB_ASSUME
#undef HPB_ASSERT
#undef HPB_UNREACHABLE
#undef HPB_SETJMP
#undef HPB_LONGJMP
#undef HPB_PTRADD
#undef HPB_MUSTTAIL
#undef HPB_FASTTABLE_SUPPORTED
#undef HPB_FASTTABLE_MASK
#undef HPB_FASTTABLE
#undef HPB_FASTTABLE_INIT
#undef HPB_POISON_MEMORY_REGION
#undef HPB_UNPOISON_MEMORY_REGION
#undef HPB_ASAN
#undef HPB_ASAN_GUARD_SIZE
#undef HPB_CLANG_ASAN
#undef HPB_TREAT_PROTO2_ENUMS_LIKE_PROTO3
#undef HPB_DEPRECATED
#undef HPB_GNUC_MIN
#undef HPB_DESCRIPTOR_HPB_H_FILENAME
#undef HPB_DESC
#undef HPB_IS_GOOGLE3
#undef HPB_ATOMIC
#undef HPB_USE_C11_ATOMICS
#undef HPB_PRIVATE
